import { Container, Header } from '@/components/shared';

import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Next Pizza | Carrello',
  description: 'Generated by create next app',
};

export default function DashBoardLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-surface-beige">
      <Header
        className="border-b border-gray-200"
        hasSearch={false}
        hasCart={false}
        hasRightSide={false}
      />
      <Container>{children}</Container>
    </main>
  );
}
