import { Header } from '@/components/shared';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Pizza | Admin Panel',
  description: 'Generated by create next app',
};

export default function DashBoardLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-white">
      <Header hasSearch={false} hasCart={false} />
      {children}
    </main>
  );
}
